#!/usr/bin/env python3
"""
Generate GBA ROM tables from Python content files.

Converts runtime data structures into C arrays that can be compiled into
GBA ROM. This eliminates runtime file access and JSON parsing on GBA.

Usage:
    python tools/generate_gba_rom_tables.py --output gba_src/generated/

Output:
- rom_tiles.c/h - Map tile data
- rom_sprites.c/h - Sprite sheets
- rom_items.c/h - Item definitions
- rom_enemies.c/h - Enemy stats
- rom_dialogue.c/h - Text tables
"""

from __future__ import annotations

import argparse
import json
import os
import struct
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Tuple

# Add parent to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from content_registry import (
    CHEST_DEFS,
    ENEMY_SPAWN_DEFS,
    GROUND_ITEM_DEFS,
    NPC_DEFS,
)
from item_system import ITEM_DEFS
from maps.dungeon import DUNGEON
from maps.ruins import RUINS_APPROACH, RUINS_DEPTHS
from maps.sanctum import SANCTUM_HALLS, THRONE_ROOM
from maps.village import VILLAGE


def sanitize_c_identifier(name: str) -> str:
    """Convert name to valid C identifier."""
    safe = name.replace("-", "_").replace(" ", "_").replace(":", "_")
    # Remove non-alphanumeric
    safe = "".join(c for c in safe if c.isalnum() or c == "_")
    if safe[0].isdigit():
        safe = "_" + safe
    return safe


def color_to_gba(r: int, g: int, b: int) -> int:
    """Convert 24-bit RGB to GBA 15-bit color."""
    return ((b >> 3) << 10) | ((g >> 3) << 5) | (r >> 3)


def generate_header_guard(filename: str) -> str:
    """Generate include guard macro."""
    guard = filename.upper().replace(".", "_").replace("/", "_")
    return f"__{guard}__"


class CGenerator:
    """Generate C source files."""

    def __init__(self, output_dir: Path):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.indent = "    "

    def write_file(self, name: str, content: str) -> Path:
        """Write a C source file."""
        path = self.output_dir / name
        with open(path, "w") as f:
            f.write(content)
        return path

    def generate_header(self, name: str, includes: List[str] = None) -> str:
        """Generate C header content."""
        guard = generate_header_guard(name)
        lines = [
            f"/* Auto-generated by {Path(__file__).name} - Do not edit manually */",
            "#pragma once",
            "",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
        ]

        if includes:
            for inc in includes:
                lines.append(f'#include "{inc}"')
            lines.append("")

        return "\n".join(lines)

    def generate_footer(self, name: str) -> str:
        """Generate C footer with #endif."""
        guard = generate_header_guard(name)
        return f"\n#endif /* {guard} */\n"


class TilemapGenerator:
    """Generate tilemap data for GBA BG layers."""

    def __init__(self, generator: CGenerator):
        self.gen = generator

    def _pack_tilemap(self, map_data: Dict) -> Tuple[bytes, int, int]:
        """Pack tilemap into binary format."""
        width = map_data["width"]
        height = map_data["height"]
        ground = map_data["ground"]

        # GBA screen entry format: 10-bit tile index + palette + flip bits
        # Pack as 16-bit values
        data = bytearray()

        for row in ground:
            for tile_id in row:
                # Screen entry: tile index (10 bits), hflip, vflip, palette (4 bits)
                screen_entry = tile_id & 0x3FF
                data.extend(struct.pack("<H", screen_entry))

        return bytes(data), width, height

    def generate(self, maps: Dict[str, Dict]) -> Tuple[str, str]:
        """Generate C files for tilemaps."""
        # Header
        h_content = self.gen.generate_header("rom_tiles.h")
        h_content += "\n#include <gba_types.h>\n\n"

        # Source
        c_content = f'/* Auto-generated tilemap data */\n#include "rom_tiles.h"\n\n'

        for map_name, map_data in maps.items():
            var_name = sanitize_c_identifier(map_name)

            # Pack data
            packed, width, height = self._pack_tilemap(map_data)
            collision_size = (width * height + 7) // 8

            # Generate C array
            h_content += f"#define {var_name.upper()}_WIDTH {width}\n"
            h_content += f"#define {var_name.upper()}_HEIGHT {height}\n"
            h_content += f"#define {var_name.upper()}_SIZE {len(packed)}\n"
            h_content += f"extern const u16 {var_name}_tiles[{len(packed) // 2}];\n"
            h_content += (
                f"extern const u8 {var_name}_collision[{collision_size}];\n\n"
            )

            # Write data as C array
            c_content += f"/* {map_name}: {width}x{height} */\n"
            c_content += f"const u16 {var_name}_tiles[{len(packed) // 2}] = {{\n"

            for i in range(0, len(packed), 32):
                line_data = packed[i : i + 32]
                hex_vals = ", ".join(
                    f"0x{v:04x}"
                    for v in struct.unpack("<" + "H" * (len(line_data) // 2), line_data)
                )
                c_content += f"    {hex_vals},\n"

            c_content += "};\n\n"

            # Collision data (bit-packed)
            c_content += f"const u8 {var_name}_collision[{collision_size}] = {{\n"
            collision = map_data.get("collision", [])
            collision_bytes = bytearray((width * height + 7) // 8)
            for y, row in enumerate(collision):
                for x, collidable in enumerate(row):
                    if collidable:
                        bit = y * width + x
                        collision_bytes[bit // 8] |= 1 << (bit % 8)

            for i in range(0, len(collision_bytes), 16):
                chunk = collision_bytes[i : i + 16]
                hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
                c_content += f"    {hex_vals},\n"
            c_content += "};\n\n"

        h_content += self.gen.generate_footer("rom_tiles.h")

        return c_content, h_content


class ItemTableGenerator:
    """Generate item definition tables."""

    ITEM_TYPE_BY_CATEGORY = {
        "weapon": 0,
        "armor": 1,
        "consumable": 2,
        "material": 3,
        "key_item": 4,
        "accessory": 5,
    }
    RARITY_BY_TIER = {
        "common": 0,
        "uncommon": 1,
        "rare": 2,
        "epic": 3,
        "legendary": 4,
        "mythic": 5,
    }

    def __init__(self, generator: CGenerator):
        self.gen = generator

    def _item_type(self, item_def: Dict) -> int:
        category = item_def.get("category", item_def.get("type", "key_item"))
        return self.ITEM_TYPE_BY_CATEGORY.get(str(category), self.ITEM_TYPE_BY_CATEGORY["key_item"])

    def _rarity(self, item_def: Dict) -> int:
        rarity = item_def.get("rarity", item_def.get("loot_tier", "common"))
        if isinstance(rarity, str):
            return self.RARITY_BY_TIER.get(rarity, 0)
        return int(rarity)

    def _stat_bonus(self, item_def: Dict) -> int:
        stats = item_def.get("stats", {})
        if not isinstance(stats, dict):
            return int(item_def.get("damage", item_def.get("defense", 0)))

        priority = ("attack", "defense", "speed", "attack_range", "magic_amp")
        for key in priority:
            if key in stats:
                return max(0, int(round(float(stats[key]))))
        return 0

    def generate(self, item_defs: Dict) -> Tuple[str, str]:
        """Generate C files for item definitions."""
        items = [
            (str(item_id), item_def)
            for item_id, item_def in item_defs.items()
            if isinstance(item_def, dict)
        ]

        h_content = self.gen.generate_header("rom_items.h")
        h_content += "\n#include <gba_types.h>\n\n"
        h_content += "/* Item types */\n"
        h_content += "#define ITEM_TYPE_WEAPON 0\n"
        h_content += "#define ITEM_TYPE_ARMOR 1\n"
        h_content += "#define ITEM_TYPE_CONSUMABLE 2\n"
        h_content += "#define ITEM_TYPE_MATERIAL 3\n"
        h_content += "#define ITEM_TYPE_KEY 4\n\n"
        h_content += "#define ITEM_TYPE_ACCESSORY 5\n\n"

        h_content += "/* Rarity tiers */\n"
        h_content += "#define ITEM_RARITY_COMMON 0\n"
        h_content += "#define ITEM_RARITY_UNCOMMON 1\n"
        h_content += "#define ITEM_RARITY_RARE 2\n"
        h_content += "#define ITEM_RARITY_EPIC 3\n"
        h_content += "#define ITEM_RARITY_LEGENDARY 4\n"
        h_content += "#define ITEM_RARITY_MYTHIC 5\n\n"

        c_content = f'/* Auto-generated item tables */\n#include "rom_items.h"\n\n'

        # Generate item struct definition
        h_content += "typedef struct {\n"
        h_content += "    u16 id;\n"
        h_content += "    u8 type;\n"
        h_content += "    u8 rarity;\n"
        h_content += "    u16 value;\n"
        h_content += "    u16 stat_bonus;\n"
        h_content += "    u8 stack_size;\n"
        h_content += "} ItemDef;\n\n"

        # Generate item count
        h_content += f"#define NUM_ITEMS {len(items)}\n"
        h_content += "extern const ItemDef ITEM_TABLE[NUM_ITEMS];\n"
        h_content += "extern const char* ITEM_NAMES[NUM_ITEMS];\n\n"

        h_content += "typedef enum {\n"
        for item_index, (item_id, _) in enumerate(items):
            h_content += f"    ITEM_{sanitize_c_identifier(item_id).upper()} = {item_index},\n"
        h_content += "} ItemId;\n\n"

        # Generate item table
        c_content += "const ItemDef ITEM_TABLE[NUM_ITEMS] = {\n"

        for item_index, (item_id, item_def) in enumerate(items):
            item_type = self._item_type(item_def)
            rarity = self._rarity(item_def)
            value = int(item_def.get("value", 0))
            stat = self._stat_bonus(item_def)
            stack = int(item_def.get("stack_max", item_def.get("stack", 1)))

            c_content += f"    /* {item_id} */ {{{item_index}, {item_type}, {rarity}, {value}, {stat}, {stack}}},\n"

        c_content += "};\n\n"

        # Generate name table
        c_content += "const char* ITEM_NAMES[NUM_ITEMS] = {\n"
        for item_id, _ in items:
            c_content += f'    "{item_id}",\n'
        c_content += "};\n\n"

        h_content += self.gen.generate_footer("rom_items.h")

        return c_content, h_content


class EnemyTableGenerator:
    """Generate enemy stat tables."""

    def __init__(self, generator: CGenerator):
        self.gen = generator

    def generate(self, spawn_defs: Dict) -> Tuple[str, str]:
        """Generate C files for enemy stats."""
        h_content = self.gen.generate_header("rom_enemies.h")
        h_content += "\n#include <gba_types.h>\n\n"
        h_content += "typedef struct {\n"
        h_content += "    u8 type_id;\n"
        h_content += "    u8 hp;\n"
        h_content += "    u8 damage;\n"
        h_content += "    u8 speed;\n"
        h_content += "    u16 xp_reward;\n"
        h_content += "    u8 ai_type;\n"
        h_content += "} EnemyDef;\n\n"

        c_content = f'/* Auto-generated enemy tables */\n#include "rom_enemies.h"\n\n'

        # Collect unique enemy types
        enemy_types: Dict[str, Dict] = {}
        for spawn in spawn_defs.values():
            if isinstance(spawn, dict):
                enemy_type = spawn.get("type", "unknown")
                if enemy_type not in enemy_types:
                    enemy_types[enemy_type] = spawn

        h_content += f"#define NUM_ENEMY_TYPES {len(enemy_types)}\n\n"
        h_content += "extern const EnemyDef ENEMY_TABLE[NUM_ENEMY_TYPES];\n\n"

        # Generate enum
        h_content += "enum EnemyType {\n"
        for i, name in enumerate(enemy_types.keys()):
            h_content += f"    ENEMY_{sanitize_c_identifier(name).upper()} = {i},\n"
        h_content += "};\n\n"

        # Generate table
        c_content += "const EnemyDef ENEMY_TABLE[NUM_ENEMY_TYPES] = {\n"
        for name, data in enemy_types.items():
            type_id = list(enemy_types.keys()).index(name)
            hp = data.get("hp", 3)
            damage = data.get("damage", 1)
            speed = int(data.get("speed", 2.0) * 16)  # Fixed-point speed
            xp = data.get("xp", 10)
            ai = 0  # Default AI type

            c_content += f"    /* {name} */ {{{type_id}, {hp}, {damage}, {speed}, {xp}, {ai}}},\n"
        c_content += "};\n\n"

        h_content += self.gen.generate_footer("rom_enemies.h")

        return c_content, h_content


class NPCDialogueGenerator:
    """Generate dialogue text tables."""

    def __init__(self, generator: CGenerator):
        self.gen = generator

    def generate(self, npc_defs: Dict) -> Tuple[str, str]:
        """Generate C files for NPC dialogue."""
        h_content = self.gen.generate_header("rom_dialogue.h")
        h_content += "\n#include <gba_types.h>\n\n"
        h_content += "typedef struct {\n"
        h_content += "    u16 npc_id;\n"
        h_content += "    u8 num_lines;\n"
        h_content += "    const char** lines;\n"
        h_content += "} DialogueEntry;\n\n"

        c_content = (
            f'/* Auto-generated dialogue tables */\n#include "rom_dialogue.h"\n\n'
        )

        # Collect dialogue
        dialogues: List[Tuple[str, List[str]]] = []
        for npc_id, npc_data in npc_defs.items():
            if isinstance(npc_data, dict):
                lines = npc_data.get("dialogue", [])
                if isinstance(lines, str):
                    lines = [lines]
                if lines:
                    dialogues.append((npc_id, lines))

        h_content += f"#define NUM_DIALOGUE_ENTRIES {len(dialogues)}\n\n"
        h_content += (
            "extern const DialogueEntry DIALOGUE_TABLE[NUM_DIALOGUE_ENTRIES];\n\n"
        )

        # Generate individual dialogue arrays
        for npc_id, lines in dialogues:
            safe_name = sanitize_c_identifier(str(npc_id))
            c_content += f"static const char* {safe_name}_lines[] = {{\n"
            for line in lines:
                c_content += f'    "{line}",\n'
            c_content += "};\n\n"

        # Generate table
        c_content += "const DialogueEntry DIALOGUE_TABLE[NUM_DIALOGUE_ENTRIES] = {\n"
        for i, (npc_id, lines) in enumerate(dialogues):
            safe_name = sanitize_c_identifier(str(npc_id))
            c_content += (
                f"    /* {npc_id} */ {{{i}, {len(lines)}, {safe_name}_lines}},\n"
            )
        c_content += "};\n\n"

        h_content += self.gen.generate_footer("rom_dialogue.h")

        return c_content, h_content


def main():
    parser = argparse.ArgumentParser(description="Generate GBA ROM tables")
    parser.add_argument(
        "--output",
        "-o",
        type=str,
        default="gba_src/generated",
        help="Output directory for generated files",
    )
    args = parser.parse_args()

    print("Generating GBA ROM tables...")

    generator = CGenerator(Path(args.output))

    # Tilemaps
    print("  - Generating tilemaps...")
    maps = {
        "village": VILLAGE,
        "dungeon": DUNGEON,
        "ruins_approach": RUINS_APPROACH,
        "ruins_depths": RUINS_DEPTHS,
        "sanctum_halls": SANCTUM_HALLS,
        "throne_room": THRONE_ROOM,
    }
    tile_gen = TilemapGenerator(generator)
    c_tiles, h_tiles = tile_gen.generate(maps)
    generator.write_file("rom_tiles.c", c_tiles)
    generator.write_file("rom_tiles.h", h_tiles)

    # Items
    print("  - Generating item tables...")
    item_gen = ItemTableGenerator(generator)
    c_items, h_items = item_gen.generate(ITEM_DEFS)
    generator.write_file("rom_items.c", c_items)
    generator.write_file("rom_items.h", h_items)

    # Enemies
    print("  - Generating enemy tables...")
    enemy_gen = EnemyTableGenerator(generator)
    c_enemies, h_enemies = enemy_gen.generate(ENEMY_SPAWN_DEFS)
    generator.write_file("rom_enemies.c", c_enemies)
    generator.write_file("rom_enemies.h", h_enemies)

    # Dialogue
    print("  - Generating dialogue tables...")
    dialogue_gen = NPCDialogueGenerator(generator)
    c_dialogue, h_dialogue = dialogue_gen.generate(NPC_DEFS)
    generator.write_file("rom_dialogue.c", c_dialogue)
    generator.write_file("rom_dialogue.h", h_dialogue)

    print(f"\nGenerated files in: {args.output}")
    print("\nFiles generated:")
    for f in sorted(generator.output_dir.glob("*")):
        size = f.stat().st_size
        print(f"  {f.name}: {size} bytes")

    # Total size estimate
    total = sum(f.stat().st_size for f in generator.output_dir.glob("*.c"))
    print(f"\nTotal ROM data: {total} bytes ({total / 1024:.1f} KB)")
    print(f"GBA cartridge capacity: 4-32 MB")
    print(f"Usage: {(total / (4 * 1024 * 1024)) * 100:.2f}% of 4MB cart")


if __name__ == "__main__":
    main()
