"""
Asset Manager for Mythical.

Loads statically compiled assets (.png and metadata) generated by tools/compile_assets.py
Used by PyGame client. The GBA engine uses similar raw binary loaders.
"""
import os
import json
import pygame

compiled_assets = {}

def get_asset_dir():
    # Go up from runtime/ to root, then assets/compiled
    return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "assets", "compiled"))

def load_sprite_sheet(category_id: str) -> dict:
    """
    Loads a compiled sprite sheet from disk via metadata.
    category_id: e.g. "player", "animal_boar", "boss_1"
    """
    if category_id in compiled_assets:
        return compiled_assets[category_id]
        
    asset_dir = os.path.join(get_asset_dir(), category_id)
    if not os.path.exists(asset_dir):
        print(f"[warning] Compiled asset missing for: {category_id}")
        return None
        
    meta_path = os.path.join(asset_dir, "meta.json")
    if not os.path.exists(meta_path):
        return None
        
    with open(meta_path, "r") as f:
        meta = json.load(f)
        
    animations = {}
    for anim_name, anim_data in meta["animations"].items():
        frames = []
        for frame_file in anim_data["frames"]:
            frame_path = os.path.join(asset_dir, frame_file)
            surf = pygame.image.load(frame_path).convert_alpha()
            frames.append(surf)
        animations[anim_name] = frames
        
    compiled_assets[category_id] = animations
    return animations

def get_frame(category_id: str, anim_name: str, frame_index: int) -> pygame.Surface:
    """Returns a specific frame from a loaded sprite sheet."""
    sheet = load_sprite_sheet(category_id)
    if not sheet or anim_name not in sheet:
        return None
    frames = sheet[anim_name]
    return frames[frame_index % len(frames)]
