"""Bake project PNGs into a C++ header of raw RGBA bytes.

Output: a single header with a sprite table (name, w, h, pixel offset) and a
giant RGBA pixel array. C++ side reads this and creates SDL_Textures — no
runtime PNG dependency.

Mapping of logical sprite names mirrors SpriteId in src/core/types.h and the
python AssetManager in asset_manager.py so the two ports share the same art.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
EXTRACTED = ROOT / "assets" / "extracted"

# Logical name -> (folder, filename).
# Keep names in lockstep with the SpriteId enum tags used by the renderer.
SPRITES: list[tuple[str, str, str]] = [
    ("Char0", "characters", "char_0.png"),
    ("Char1", "characters", "char_1.png"),
    ("Char2", "characters", "char_2.png"),
    ("Char3", "characters", "char_3.png"),
    ("Char4", "characters", "char_4.png"),

    ("TowerArrow1",     "towers", "tower_0_0.png"),
    ("TowerArrow2",     "towers", "tower_0_1.png"),
    ("TowerArrow3",     "towers", "tower_0_2.png"),
    ("TowerCannon1",    "towers", "tower_1_0.png"),
    ("TowerCannon2",    "towers", "tower_1_1.png"),
    ("TowerCannon3",    "towers", "tower_1_2.png"),
    ("TowerIce1",       "towers", "tower_2_0.png"),
    ("TowerIce2",       "towers", "tower_2_1.png"),
    ("TowerIce3",       "towers", "tower_2_2.png"),
    # Lightning/Flame reuse cannon/ice art and get tinted at draw time.
    ("TowerLightning1", "towers", "tower_1_0.png"),
    ("TowerLightning2", "towers", "tower_1_1.png"),
    ("TowerLightning3", "towers", "tower_1_2.png"),
    ("TowerFlame1",     "towers", "tower_2_0.png"),
    ("TowerFlame2",     "towers", "tower_2_1.png"),
    ("TowerFlame3",     "towers", "tower_2_2.png"),

    ("TileGrass",     "tileset1", "green_edge_1.png"),
    ("TileGrassAlt",  "tileset1", "green_0_0.png"),
    ("TilePath",      "tileset1", "sand_0_0.png"),
    ("TilePathAlt",   "tileset1", "sand_0_1.png"),
    ("TileRock",      "tileset1", "green_edge_1.png"),
    ("TileWater",     "tileset1", "cyan_0_0.png"),
    ("TileTree",      "tileset1", "green_edge_1.png"),
    ("TileSpawn",     "tileset1", "sand_0_0.png"),
    ("TileBase",      "tileset1", "cyan_0_0.png"),
    ("TileTowerBase", "tileset1", "sand_edge_1.png"),

    ("PropTreeLarge", "props", "prop_0_0.png"),
    ("PropTreeSmall", "props", "prop_1_0.png"),
    ("PropBush",      "props", "prop_2_0.png"),
    ("PropRockLarge", "props", "prop_4_0.png"),
    ("PropRockSmall", "props", "prop_4_1.png"),
    ("PropLog",       "props", "prop_5_1.png"),
]


def main(out_path: str) -> int:
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)

    entries = []
    pixel_blob = bytearray()
    for name, folder, filename in SPRITES:
        path = EXTRACTED / folder / filename
        if not path.exists():
            print(f"warning: missing {path}", file=sys.stderr)
            # Emit a 1x1 magenta so the C++ table stays dense.
            w, h = 1, 1
            rgba = bytes([255, 0, 255, 255])
        else:
            img = Image.open(path).convert("RGBA")
            w, h = img.size
            rgba = img.tobytes()
        offset = len(pixel_blob)
        pixel_blob.extend(rgba)
        entries.append((name, w, h, offset))

    with out.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/bake_sprites.py — do not edit.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstddef>\n#include <cstdint>\n\n")

        f.write("struct BakedSprite {\n")
        f.write("    const char* name;\n")
        f.write("    int w;\n")
        f.write("    int h;\n")
        f.write("    std::size_t pixel_offset;\n")
        f.write("};\n\n")

        f.write(f"constexpr int BAKED_SPRITE_COUNT = {len(entries)};\n\n")
        f.write("inline const BakedSprite BAKED_SPRITES[BAKED_SPRITE_COUNT] = {\n")
        for name, w, h, off in entries:
            f.write(f'    {{"{name}", {w}, {h}, {off}}},\n')
        f.write("};\n\n")

        f.write(f"inline constexpr std::size_t BAKED_PIXEL_BYTES = {len(pixel_blob)};\n")
        f.write("inline const unsigned char BAKED_PIXELS[] = {\n")
        line = []
        for i, byte in enumerate(pixel_blob):
            line.append(f"0x{byte:02x}")
            if (i + 1) % 16 == 0:
                f.write("    " + ",".join(line) + ",\n")
                line = []
        if line:
            f.write("    " + ",".join(line) + ",\n")
        f.write("};\n")

    print(f"baked {len(entries)} sprites, {len(pixel_blob)} pixel bytes -> {out}")
    return 0


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else str(ROOT / "build" / "generated" / "baked_sprites.h")
    sys.exit(main(out))
